Task 2.3
DerekAyala/Coherent-Solutions-Tasks pull request #4
Opened 2023-11-09 15:39 UTC by DerekAyala

2023-11-10 11:03 UTC, IgorKheidorov requested changes
Redesign the architecture

2023-11-10 11:03 UTC, IgorKheidorov commented on HW 02/Task 2.3/Lecture.cs
> +namespace Task_2._3
Fix design, add common base class for training, Lecture, practical lesson (base class (BaseEntity) will include description). For Lecture and practical lesson add one more base class (for example, Lesson) -> 
class  Lecture: Lesson: BaseEntity 
class PracticalLesson: Lesson: BaseEntity.

2023-11-10 11:03 UTC, IgorKheidorov commented on HW 02/Task 2.3/Training.cs
> +        private String textDescription;
private Lesson[] _lessons;

2023-11-10 11:03 UTC, IgorKheidorov commented on HW 02/Task 2.3/Training.cs
> +            {
Implement Clone for Lectures and PracticalLesson an simply:
 clonedTraining.Add(item.Clone());

2023-11-13 09:11 UTC, IgorKheidorov requested changes
Fix comments, if you as made PR for task 2.3> why I see files for task 2.1 in it? ))))

2023-11-13 09:11 UTC, IgorKheidorov commented on HW 02/Task 2.3/Lecture.cs
> +        {
return  new Lecture(Topic, TextDescription);

2023-11-13 09:11 UTC, IgorKheidorov commented on HW 02/Task 2.3/Lesson.cs
> +        public Lesson(String textDescription)
Fix intensions (Code style)

2023-11-13 09:11 UTC, IgorKheidorov commented on HW 02/Task 2.3/Lesson.cs
> +
Add ICloneable here, to Lesson

2023-11-13 09:11 UTC, IgorKheidorov commented on HW 02/Task 2.3/Training.cs
> +                if (item is Lecture lecture)
clonedTraining.Add((Lesson)item.Clone());

If you make Lesson ICloneable (base class for Lecture and PracticalLesson), no need to use if... else  statements

2023-11-17 03:28 UTC, DerekAyala commented
Sorry about files from 2.1, on 2.1 I update git ignore to remove binary files, and I merge main on this brach to get that git ignore

2023-11-17 07:58 UTC, IgorKheidorov requested changes

2023-11-17 07:58 UTC, IgorKheidorov commented on HW 02/Task 2.3/PracticalLesson.cs
> +{
public class PracticalLesson : Lesson. Do not add ICloneable here, it is inherited  from Lesson,

2023-11-17 07:58 UTC, IgorKheidorov commented on HW 02/Task 2.3/Lesson.cs
> +
Has to be virtual to be overridden in PracticalLesson and Lecture

2023-11-17 07:58 UTC, IgorKheidorov commented on HW 02/Task 2.3/Training.cs
> +                clonedTraining.Add((Lesson)item.Clone());
Clone from Lesson is called here, not from PracticalLecture and Lecture, thus this is not a deep cloning, you can check this fact ))). Make Clone() in Lesson virtual

2023-11-21 12:47 UTC, IgorKheidorov approved these changes
Now its cool!

2023-11-21 16:27 UTC, merged